openapi: 3.0.0
info:
  title: TODO App
  description: REST API for TODO entries management application
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
components:
  schemas:
    TodoEntry:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
    NewTodoEntry:
      type: object
      properties:
        name:
          type: string
      required:
        - name
paths:
  /entries:
    get:
      tags:
        - CRUD
      summary: Get all TODO entries
      responses:
        200:
          description: All TODO entries read successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoEntry'
    post:
      tags:
        - CRUD
      summary: Add new TODO entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodoEntry'
      responses:
        201:
          description: TODO entry added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
  /entries/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: TODO entry ID
        schema:
          type: integer
    get:
      tags:
        - CRUD
      summary: Get TODO entry by its ID
      responses:
        200:
          description: TODO entry read successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        404:
          description: TODO entry not found
    patch:
      tags:
        - CRUD
      summary: Update TODO entry
      requestBody:
        description: Updated entry
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodoEntry'
      responses:
        200:
          description: TODO entry updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoEntry'
        404:
          description: TODO entry with given id not found
    delete:
      tags:
        - CRUD
      summary: Delete TODO entry
      responses:
        204:
          description: TODO entry deleted successfully
        404:
          description: TODO entry not found